gabia-intern-team-2/gabia-project-gyebalja-api

src/main/java/com/gabia/gyebalja/controller/CommentApiController.java
src/main/java/com/gabia/gyebalja/domain/Comment.java
src/main/java/com/gabia/gyebalja/dto/CommentDto.java
src/main/java/com/gabia/gyebalja/repository/CommentRepository.java
src/main/java/com/gabia/gyebalja/service/CommentService.java
src/test/java/com/gabia/gyebalja/comment/CommentTest.java

**댓글**
- 댓글 단건 CRUD 기능 구현
- 테스트 코드 작성 (통과)

댓글 - 댓글 단건 CURD 기능 구현

---

build.gradle
src/main/java/com/gabia/gyebalja/controller/BoardApiController.java
src/main/java/com/gabia/gyebalja/domain/Board.java
src/main/java/com/gabia/gyebalja/dto/BoardDto.java
src/main/java/com/gabia/gyebalja/repository/BoardRepository.java
src/main/java/com/gabia/gyebalja/service/BoardService.java
src/test/java/com/gabia/gyebalja/board/BoardTest.java

게시판 구현 
- 게시글 단건 CRUD 기능 구현
- 테스트 코드 작성 (통과)
- 게시글 연관 기능 - 댓글 조회, 사용자 조회 등 구현 X
- Mysql 쿼리 보기 위해 build.gradle, application.yml 파일 설정

개발: 게시판 단건 CRUD 기능 구현

---

src/main/java/com/gabia/gyebalja/controller/CommentApiController.java
src/main/java/com/gabia/gyebalja/domain/Comment.java
src/main/java/com/gabia/gyebalja/dto/CommentDto.java
src/main/java/com/gabia/gyebalja/repository/CommentRepository.java
src/main/java/com/gabia/gyebalja/service/CommentService.java
src/test/java/com/gabia/gyebalja/comment/CommentTest.java

**댓글 구현**
- 댓글 단건 CRUD 기능 구현
- 테스트 코드 작성 (통과)
- 댓글 연관 기능 - 사용자 조회 등 구현 X

개발: 댓글 단건 CRUD 기능 구현

---

src/main/java/com/gabia/gyebalja/domain/Board.java
src/main/java/com/gabia/gyebalja/domain/BoardImg.java
src/main/java/com/gabia/gyebalja/domain/Comment.java
src/main/java/com/gabia/gyebalja/domain/Department.java
src/main/java/com/gabia/gyebalja/domain/Likes.java

**엔티티 클래스 구현 완료(Board, BoardImg, Comment, Department, Likes)**
- Board
- BoardImg
- Comment
- Department
- Likes

엔티티 클래스 구현 완료(Board, BoardImg, Comment, Department, Likes)

---

src/main/java/com/gabia/gyebalja/domain/Category.java
src/main/java/com/gabia/gyebalja/domain/EduTag.java
src/main/java/com/gabia/gyebalja/domain/Education.java
src/main/java/com/gabia/gyebalja/domain/EducationType.java
src/main/java/com/gabia/gyebalja/domain/Tag.java
src/main/java/com/gabia/gyebalja/domain/User.java
src/main/java/com/gabia/gyebalja/domain/UserGender.java

- User
- Education
-  Category
- Tag
- EduTag

엔티티 클래스 구현 완료

---

src/main/java/com/gabia/gyebalja/repository/CategoryRepository.java
src/main/java/com/gabia/gyebalja/repository/EduTagRepository.java
src/main/java/com/gabia/gyebalja/repository/EducationRepository.java
src/main/java/com/gabia/gyebalja/repository/TagRepository.java
src/main/java/com/gabia/gyebalja/repository/UserRepository.java

- UserRepository
- TagRepository
- EduTagRepository
- CategoryRepository
- EducationRepository

feature/#21 엔티티(User, Tag, EduTag, Category, Education) 기본 Repository 구현 완료

---

src/main/java/com/gabia/gyebalja/domain/Board.java
src/main/java/com/gabia/gyebalja/domain/BoardImg.java
src/main/java/com/gabia/gyebalja/domain/Comment.java
src/main/java/com/gabia/gyebalja/domain/Department.java
src/main/java/com/gabia/gyebalja/domain/Likes.java
src/main/java/com/gabia/gyebalja/repository/BoardImgRepository.java
src/main/java/com/gabia/gyebalja/repository/DepartmentRepository.java
src/main/java/com/gabia/gyebalja/repository/LikesRepository.java

**feature/#15 에서 작성한 엔티티 클래스 레포지토리 구현**
> Board, BoardImg, Comment, Likes, Department 엔티티 클래스 레포지토리 구현
> Board, Comment 레포지토리 이전에 작성 (반영되어 있음)
> ToString 어노테이션 삭제
- Board
- BoardImg
- Comment
- Likes
- Department

Board, BoardImg, Comment, Likes, Department 엔티티 클래스 레포지토리 구현

---

src/main/java/com/gabia/gyebalja/domain/Category.java
src/main/java/com/gabia/gyebalja/domain/EduTag.java
src/main/java/com/gabia/gyebalja/domain/Education.java
src/main/java/com/gabia/gyebalja/domain/Tag.java
src/main/java/com/gabia/gyebalja/domain/User.java

엔티티 클래스 빌더 생성자 작성
-User
-Education
-EduTag
-Tag
-Category

#26 엔티티 기본 Builder 생성자 추가 -> User, Education, EduTag, Tag, Category

---

src/main/java/com/gabia/gyebalja/domain/Board.java
src/main/java/com/gabia/gyebalja/domain/BoardImg.java
src/main/java/com/gabia/gyebalja/domain/Comment.java
src/main/java/com/gabia/gyebalja/domain/Department.java
src/main/java/com/gabia/gyebalja/domain/Likes.java

**#25 엔티티 클래스 빌더 생성자 작성 -> Board, BoardImg, Comment, Department, Likes 작성**
Entity Repository를 테스트하기 위해 엔티티들의 빌더 생성자 필요
테스트를 위한 빌더 생성자 작성
- Board
- Comment
- Likes
- Department
- BoardImg

#25 엔티티 클래스 빌더 생성자 작성 -> Board, BoardImg, Comment, Department, Likes 작성

---

src/main/java/com/gabia/gyebalja/domain/Board.java
src/test/java/com/gabia/gyebalja/board/BoardRepositoryTest.java

**#24 테스트 코드 작성 - BoardRepository (기본적인 CRUD)**
BoardRepository가 잘 작동하는지 기본적인 CRUD만 테스트
- Create
- Retrieve (Read)
- Update
- Delete
> **Board 엔티티 클래스 Long views -> int views로 수정했습니다.**

#24 테스트 코드 작성 - BoardRepository (기본적인 CRUD)

---

src/test/java/com/gabia/gyebalja/comment/CommentRepositoryTest.java

#33 테스트 코드 작성 - CommentRepository (기본적인 CRUD)
Spring Data Jpa가 제공하는 기본적인 CRUD 검증 테스트
- Create
- Retrieve (Read)
- Update
- Delete
> BoardRepositoryTest 와 동일한 방법입니다.

#33 테스트 코드 작성 - CommentRepository (기본적인 CRUD)

---

src/main/java/com/gabia/gyebalja/domain/Education.java
src/test/java/com/gabia/gyebalja/education/EducationRepositoryTest.java

- domain/Education 
제목, 내용 변경 메서드 추가 
- EducationRepositoryTest
CRUD 테스트 코드 작성 완료 (findById, findAll, delete, update, count, save)

#29 Spring Data Jpa 기본적인 CRUD 테스트 코드 작성 완료

---

src/main/java/com/gabia/gyebalja/controller/BoardApiController.java
src/main/java/com/gabia/gyebalja/controller/CommentApiController.java
src/main/java/com/gabia/gyebalja/domain/Department.java
src/main/java/com/gabia/gyebalja/dto/BoardDto.java
src/main/java/com/gabia/gyebalja/dto/CommentDto.java
src/main/java/com/gabia/gyebalja/service/BoardService.java
src/main/java/com/gabia/gyebalja/service/CommentService.java
src/test/java/com/gabia/gyebalja/board/BoardTest.java
src/test/java/com/gabia/gyebalja/comment/CommentTest.java
src/test/java/com/gabia/gyebalja/department/DepartmentRepositoryTest.java

**테스트 코드 작성 - DepartmentRepository (기본적인 CRUD)**
Spring Data Jpa가 제공하는 기본적인 CRUD 검증 테스트
- Create
- Retrieve (Read)
- Update
- Delete
> update 테스트 위해 Department 엔티티에 change메소드 추가했습니다.
> BoardRepositoryTest 와 동일한 방법입니다.

#31 테스트 코드 작성 - DepartmentRepository (기본적인 CRUD)

---

src/test/java/com/gabia/gyebalja/likes/LikesRepositoryTest.java

Spring Data Jpa가 제공하는 기본적인 CRUD 검증 테스트
- Create
- Retrieve (Read)
- Update
- Delete

#35 테스트 코드 작성 - LikesRepository (기본적인 CRUD)

---

src/main/java/com/gabia/gyebalja/domain/User.java
src/test/java/com/gabia/gyebalja/education/EducationRepositoryTest.java
src/test/java/com/gabia/gyebalja/user/UserRepositoryTest.java

Spring Data Jpa가 제공하는 기본적은 CRUD 테스트
- UserRepositoryTest 추가 
- User 엔티티에 비밀번호 변경 비즈니스로직 추가
- EducationRepositoryTest 일부 수정

#42 테스트 코드 작성 - UserRepositoryTest (기본적인 CRUD)

---

src/main/java/com/gabia/gyebalja/domain/Category.java
src/main/java/com/gabia/gyebalja/domain/EduTag.java
src/main/java/com/gabia/gyebalja/domain/Education.java
src/main/java/com/gabia/gyebalja/domain/Tag.java
src/main/java/com/gabia/gyebalja/domain/User.java

- User
- Tag
- Education
- Category 
양방향 -> 단방향으로 수정 완료

#45 Category, Education, Tag, User엔티티 양방향 -> 단방향으로 수정

---

src/main/java/com/gabia/gyebalja/GyebaljaApplication.java
src/main/java/com/gabia/gyebalja/domain/BaseTime.java
src/main/java/com/gabia/gyebalja/domain/Board.java
src/main/java/com/gabia/gyebalja/domain/BoardImg.java
src/main/java/com/gabia/gyebalja/domain/Comment.java
src/main/java/com/gabia/gyebalja/domain/Department.java
src/main/java/com/gabia/gyebalja/domain/Likes.java

**Board, Comment, Department, Likes, BoardImg 엔티티 양방향 -> 단방향 수정 | Auditing 기능 추가**
- Board
- Comment
- Department
- Likes
- BoardImg
단방향으로 모두 수정
Auditing 기능 추가

#44 Board, Comment, Department, Likes, BoardImg 엔티티 양방향 -> 단방향 수정 | Auditing 기능 추가 

---

src/main/java/com/gabia/gyebalja/GyebaljaApplication.java
src/main/java/com/gabia/gyebalja/domain/BaseTime.java
src/main/java/com/gabia/gyebalja/domain/Board.java
src/main/java/com/gabia/gyebalja/domain/BoardImg.java
src/main/java/com/gabia/gyebalja/domain/Category.java
src/main/java/com/gabia/gyebalja/domain/Comment.java
src/main/java/com/gabia/gyebalja/domain/Department.java
src/main/java/com/gabia/gyebalja/domain/EduTag.java
src/main/java/com/gabia/gyebalja/domain/Education.java
src/main/java/com/gabia/gyebalja/domain/Likes.java
src/main/java/com/gabia/gyebalja/domain/Tag.java
src/main/java/com/gabia/gyebalja/domain/User.java

Feature/entity 엔티티 클래스 작성

---

src/main/java/com/gabia/gyebalja/domain/EduTag.java
src/main/java/com/gabia/gyebalja/domain/GenderType.java
src/main/java/com/gabia/gyebalja/domain/User.java
src/test/java/com/gabia/gyebalja/board/BoardRepositoryTest.java
src/test/java/com/gabia/gyebalja/boardImg/BoardImgRepositoryTest.java
src/test/java/com/gabia/gyebalja/comment/CommentRepositoryTest.java
src/test/java/com/gabia/gyebalja/likes/LikesRepositoryTest.java
src/test/java/com/gabia/gyebalja/user/UserRepositoryTest.java

- UserGender -> GenderType
- 위 파일 이름 변경으로 인한 User 수정 
- EduTag 클래스 Table 어노테이션 추가
> GenderType, User, EduTag

#49 엔티티 클래스 구현 > 기존 UserGender Enum클래스 명 -> GenderType으로 변경

---

src/main/java/com/gabia/gyebalja/controller/LikesApiController.java
src/main/java/com/gabia/gyebalja/dto/likes/LikesRequestDto.java
src/main/java/com/gabia/gyebalja/dto/likes/LikesResponseDto.java
src/main/java/com/gabia/gyebalja/service/LikesService.java
src/test/java/com/gabia/gyebalja/likes/LikesControllerTest.java
src/test/java/com/gabia/gyebalja/likes/LikesServiceTest.java

- 파일 생성
- LikesApiController 작성 (컨트롤러)
- LikesService 작성 (서비스)

#71 Api 구현 - Likes > CRUD 

---

src/main/java/com/gabia/gyebalja/controller/LikesApiController.java
src/main/java/com/gabia/gyebalja/dto/likes/LikesRequestDto.java
src/main/java/com/gabia/gyebalja/dto/likes/LikesResponseDto.java
src/main/java/com/gabia/gyebalja/repository/LikesRepository.java
src/main/java/com/gabia/gyebalja/service/LikesService.java
src/test/java/com/gabia/gyebalja/likes/LikesControllerTest.java
src/test/java/com/gabia/gyebalja/likes/LikesServiceTest.java

Api 구현 - Likes > CRUD
- 파일 생성
- LikesApiController 작성 
- LikesService 작성
- Dto, Repository 작성
- LikesServiceTest 작성
- LikesControllerTest 작성

#71 Api 구현 - Likes > CRUD

---

src/main/java/com/gabia/gyebalja/controller/LikesApiController.java
src/main/java/com/gabia/gyebalja/dto/likes/LikesRequestDto.java
src/main/java/com/gabia/gyebalja/dto/likes/LikesResponseDto.java
src/main/java/com/gabia/gyebalja/repository/LikesRepository.java
src/main/java/com/gabia/gyebalja/service/LikesService.java
src/test/java/com/gabia/gyebalja/likes/LikesControllerTest.java
src/test/java/com/gabia/gyebalja/likes/LikesServiceTest.java

* #71 Api 구현 - Likes > CRUD - 파일 생성
* #71 Api 구현 - Likes > CRUD - LikesApiController 작성
* #71 Api 구현 - Likes > CRUD - LikesService 작성
* #71 Api 구현 - Likes > CRUD - Dto, Repository 작성
* #71 Api 구현 - Likes > CRUD LikesServiceTest 작성
* #71 Api 구현 - Likes > CRUD - LikesControllerTest 작성

#71 Api 구현 - Likes > CRUD (#75)

---

src/main/java/com/gabia/gyebalja/controller/DepartmentApiController.java
src/test/java/com/gabia/gyebalja/department/DepartmentControllerTest.java

#84 Api 작성 - Department > 컨트롤러 작성
- 컨트롤러 작성
- 컨트롤러 테스트코드 작성
(조회 부분만 작성)

#84 Api 작성 - Department > 컨트롤러 작성

---

src/main/java/com/gabia/gyebalja/service/DepartmentService.java
src/test/java/com/gabia/gyebalja/department/DepartmentServiceTest.java

#86 Api 작성 - Department > 서비스 작성
- 서비스 작성
- 서비스 테스트코드 작성
(조회 부분만 작성)

#86 Api 작성 - Department > 서비스 작성

---

src/main/java/com/gabia/gyebalja/dto/department/DepartmentRequestDto.java
src/main/java/com/gabia/gyebalja/dto/department/DepartmentResponseDto.java

#88 Api 작성 - Department > DTO 작성
- 리스폰스 DTO 작성 (DepartmentResponseDto)
- 리퀘스트 DTO 작성 (파일만 생성)
(아직까지 리퀘스트 DTO의 경우는 필요 없을 것 같아 작성하지 않음)

#88 Api 작성 - Department > DTO 작성

---

src/main/java/com/gabia/gyebalja/common/CommonExceptionHandler.java
src/main/java/com/gabia/gyebalja/common/CommonJsonFormat.java
src/main/java/com/gabia/gyebalja/common/StatusCode.java
src/main/java/com/gabia/gyebalja/dto/likes/LikesRequestDto.java
src/main/java/com/gabia/gyebalja/dto/likes/LikesResponseDto.java

#92 Api 작성 - Likes > 코드 수정
- ErrorCode -> StatusCode 파일명 수정
- 예외처리 파일 수정 (로그 출력문 수정)
- Likes DTO 수정 (NoArgsConstructor 추가)

#92 Api 작성 - Likes > 코드 수정

---

src/main/java/com/gabia/gyebalja/common/CommonExceptionHandler.java
src/main/java/com/gabia/gyebalja/common/CommonJsonFormat.java
src/main/java/com/gabia/gyebalja/common/StatusCode.java
src/main/java/com/gabia/gyebalja/controller/CommentApiController.java
src/test/java/com/gabia/gyebalja/comment/CommentControllerTest.java

#96 Api 작성 - Comment > CommonJsonFormat 적용
- CommonJsonFormat 적용
-  common 파일 변경
- 컨트롤러, 컨트롤러 테스트 코드 
-  코드 정리

#96 Api 작성 - Comment > CommonJsonFormat 적용

---

src/main/java/com/gabia/gyebalja/common/CommonExceptionHandler.java
src/main/java/com/gabia/gyebalja/common/CommonJsonFormat.java
src/main/java/com/gabia/gyebalja/common/StatusCode.java
src/main/java/com/gabia/gyebalja/controller/BoardApiController.java
src/test/java/com/gabia/gyebalja/board/BoardControllerTest.java

#98 Api 작성 - Board > CommonJsonFormat 적용
- CommonJsonFormat 적용

#98 Api 작성 - Board > CommonJsonFormat 적용

---

src/main/java/com/gabia/gyebalja/common/CommonExceptionHandler.java
src/main/java/com/gabia/gyebalja/common/CommonJsonFormat.java
src/main/java/com/gabia/gyebalja/common/StatusCode.java
src/main/java/com/gabia/gyebalja/controller/DepartmentApiController.java
src/main/java/com/gabia/gyebalja/dto/department/DepartmentRequestDto.java
src/main/java/com/gabia/gyebalja/dto/department/DepartmentResponseDto.java
src/main/java/com/gabia/gyebalja/service/DepartmentService.java
src/test/java/com/gabia/gyebalja/department/DepartmentControllerTest.java
src/test/java/com/gabia/gyebalja/department/DepartmentServiceTest.java

#101 Api 작성 - Department > 서비스 단 메소드명 변경

#101 Api 작성 - Department > 서비스 단 메소드명 변경

---

src/main/java/com/gabia/gyebalja/controller/LikesApiController.java
src/main/java/com/gabia/gyebalja/service/LikesService.java
src/test/java/com/gabia/gyebalja/likes/LikesControllerTest.java
src/test/java/com/gabia/gyebalja/likes/LikesServiceTest.java

#103 Api 작성 - Likes > 서비스 단 메소드명 변경

#103 Api 작성 - Likes > 서비스 단 메소드명 변경

---

src/main/java/com/gabia/gyebalja/controller/CommentApiController.java
src/main/java/com/gabia/gyebalja/service/CommentService.java
src/test/java/com/gabia/gyebalja/comment/CommentControllerTest.java
src/test/java/com/gabia/gyebalja/comment/CommentServiceTest.java

#106 Api 작성 - Comment > 서비스 단 메소드명 변경

#106 Api 작성 - Comment > 서비스 단 메소드명 변경

---

src/main/java/com/gabia/gyebalja/controller/DepartmentApiController.java
src/main/java/com/gabia/gyebalja/service/DepartmentService.java
src/test/java/com/gabia/gyebalja/department/DepartmentServiceTest.java

#101 Api 작성 - Department > 서비스 단 메소드명 변경

* #101 Api 작성 - Department > 서비스 단 메소드명 변경

---

src/main/java/com/gabia/gyebalja/controller/BoardApiController.java
src/main/java/com/gabia/gyebalja/service/BoardService.java
src/test/java/com/gabia/gyebalja/board/BoardControllerTest.java
src/test/java/com/gabia/gyebalja/board/BoardServiceTest.java

#108 Api 작성 - Board > 서비스 단 메소드명 변경

#108 Api 작성 - Board > 서비스 단 메소드명 변경

---

src/main/java/com/gabia/gyebalja/common/CommonExceptionHandler.java
src/main/java/com/gabia/gyebalja/common/CommonJsonFormat.java
src/main/java/com/gabia/gyebalja/common/StatusCode.java
src/main/java/com/gabia/gyebalja/controller/DepartmentApiController.java
src/main/java/com/gabia/gyebalja/dto/department/DepartmentRequestDto.java
src/main/java/com/gabia/gyebalja/dto/department/DepartmentResponseDto.java
src/main/java/com/gabia/gyebalja/service/DepartmentService.java
src/test/java/com/gabia/gyebalja/department/DepartmentControllerTest.java
src/test/java/com/gabia/gyebalja/department/DepartmentServiceTest.java
src/test/java/com/gabia/gyebalja/likes/LikesRepositoryTest.java

#83 Api 작성 - Department
- Api 컨트롤러 작성
- 서비스 작성
- 테스트 코드 작성

#83 Api 작성 - Department

---

src/main/java/com/gabia/gyebalja/controller/CategoryApiController.java
src/main/java/com/gabia/gyebalja/dto/category/CategoryRequestDto.java
src/main/java/com/gabia/gyebalja/dto/category/CategoryResponseDto.java
src/main/java/com/gabia/gyebalja/service/CategoryService.java

**#119 Api - 작성 - Category (Controller, Service, Dto) 작성**
> CategoryApiController, CategoryService, CategoryRquestDto, CategoryResponseDto 추가

#119 Api - 작성 - Category (Controller, Service, Dto) 작성

---

src/main/java/com/gabia/gyebalja/dto/board/BoardResponseDto.java
src/main/java/com/gabia/gyebalja/repository/LikesRepository.java
src/main/java/com/gabia/gyebalja/service/BoardService.java
src/test/java/com/gabia/gyebalja/board/BoardControllerTest.java
src/test/java/com/gabia/gyebalja/board/BoardServiceTest.java

#121 Api 작성 - Board
- '좋아요 개수' 세팅 로직 추가
- Board 테스트 코드 수정 (좋아요 개수 테스트 추가)

#121 Api 작성 - Board - '좋아요 개수' 세팅 로직 추가, Board 테스트 코드 수정

---

src/main/java/com/gabia/gyebalja/domain/Board.java
src/main/java/com/gabia/gyebalja/service/BoardService.java
src/test/java/com/gabia/gyebalja/board/BoardServiceTest.java

#122 Api 작성 - Board
- 조회수 증가 로직 추가

#122 Api 작성 - Board - 조회수 증가 로직 추가

---

src/main/java/com/gabia/gyebalja/controller/CategoryApiController.java
src/main/java/com/gabia/gyebalja/controller/EducationApiController.java
src/main/java/com/gabia/gyebalja/service/CategoryService.java
src/test/java/com/gabia/gyebalja/category/CategoryControllerTest.java
src/test/java/com/gabia/gyebalja/category/CategoryServiceTest.java

#124 Api 작성 - Category (테스트코드 작성)
> CategoryControllerTest, CategoryServiceTest 추가

#124 Api 작성 - Category (테스트코드 작성)

---

src/main/java/com/gabia/gyebalja/dto/board/BoardRequestDto.java
src/main/java/com/gabia/gyebalja/service/BoardService.java
src/test/java/com/gabia/gyebalja/board/BoardControllerTest.java
src/test/java/com/gabia/gyebalja/board/BoardServiceTest.java

#132 Api 작성 - Board - Request DTO 수정
Before
```
User user
Board board
```
After
```
Long userId
Long boardId
```

#132 Api 작성 - Board - Request DTO 수정

---

src/main/java/com/gabia/gyebalja/common/CommonExceptionHandler.java
src/main/java/com/gabia/gyebalja/controller/TagApiController.java
src/main/java/com/gabia/gyebalja/dto/tag/TagRequestDto.java
src/main/java/com/gabia/gyebalja/dto/tag/TagResponseDto.java
src/main/java/com/gabia/gyebalja/exception/NotExistTagException.java
src/main/java/com/gabia/gyebalja/service/TagService.java
src/test/java/com/gabia/gyebalja/category/CategoryControllerTest.java
src/test/java/com/gabia/gyebalja/category/CategoryServiceTest.java

**#134 Api 작성 - Tag (Controller, Service, Dto)**
- 데이터 존재 Exception 추가 
- 데이터베이스에 없는 데이터를 삭제하려고 할때 Exception 처리 추가

#134 Api 작성 - Tag (Controller, Service, Dto)

---

src/main/java/com/gabia/gyebalja/service/TagService.java
src/test/java/com/gabia/gyebalja/tag/TagControllerTest.java
src/test/java/com/gabia/gyebalja/tag/TagServiceTest.java

**#139 Api 작성 - Tag (테스트코드 작성)**
- Controller, Service에 대한 테스트코드 작성완료
> TagControllerTest, TagServiceTest 추가

#139 Api 작성 - Tag (테스트코드 작성)

---

src/main/java/com/gabia/gyebalja/dto/comment/CommentRequestDto.java
src/main/java/com/gabia/gyebalja/dto/comment/CommentResponseDto.java
src/main/java/com/gabia/gyebalja/dto/department/DepartmentResponseDto.java
src/main/java/com/gabia/gyebalja/repository/CommentRepository.java
src/main/java/com/gabia/gyebalja/service/LikesService.java
src/test/java/com/gabia/gyebalja/comment/CommentRepositoryTest.java
src/test/java/com/gabia/gyebalja/comment/CommentServiceTest.java
src/test/java/com/gabia/gyebalja/department/DepartmentRepositoryTest.java
src/test/java/com/gabia/gyebalja/likes/LikesControllerTest.java
src/test/java/com/gabia/gyebalja/likes/LikesRepositoryTest.java
src/test/java/com/gabia/gyebalja/likes/LikesServiceTest.java

#143 Api 작성 - 코드 정리 (Comment, Likes, Department)

#143 Api 작성 - 코드 정리 (Comment, Likes, Department)

---

src/main/java/com/gabia/gyebalja/controller/EducationApiController.java
src/main/java/com/gabia/gyebalja/domain/Education.java
src/main/java/com/gabia/gyebalja/dto/education/EducationAllResponseDto.java
src/main/java/com/gabia/gyebalja/dto/education/EducationDetailResponseDto.java
src/main/java/com/gabia/gyebalja/dto/education/EducationResponseDto.java
src/main/java/com/gabia/gyebalja/dto/edutag/EduTagRequestDto.java
src/main/java/com/gabia/gyebalja/dto/edutag/EduTagResponseDto.java
src/main/java/com/gabia/gyebalja/exception/NotExistEducationException.java
src/main/java/com/gabia/gyebalja/repository/EducationRepository.java
src/main/java/com/gabia/gyebalja/service/EducationService.java
src/test/java/com/gabia/gyebalja/education/EducationControllerTest.java
src/test/java/com/gabia/gyebalja/education/EducationServiceTest.java

**Api 작성 - Education 예외처리 및 조회 기능 수정**
- 태그 정보, 카테고리 정보 같이 보여주기
- N+1 문제 해결 및 예외처리
- 상세조회와 전체조회 ResponseDto 분리
- Education과 EduTag 양방향 관계 설정

#146 Api 작성 - Education 예외처리 및 조회 기능 수정

---

src/main/java/com/gabia/gyebalja/common/HashTagRegularExpression.java
src/main/java/com/gabia/gyebalja/controller/EducationApiController.java
src/main/java/com/gabia/gyebalja/domain/Education.java
src/main/java/com/gabia/gyebalja/dto/education/EducationAllResponseDto.java
src/main/java/com/gabia/gyebalja/dto/education/EducationRequestDto.java
src/main/java/com/gabia/gyebalja/repository/EduTagRepository.java
src/main/java/com/gabia/gyebalja/repository/EducationRepository.java
src/main/java/com/gabia/gyebalja/repository/TagRepository.java
src/main/java/com/gabia/gyebalja/service/EducationService.java
src/test/java/com/gabia/gyebalja/education/EducationControllerTest.java
src/test/java/com/gabia/gyebalja/education/EducationServiceTest.java

**#148 Api 작성 - Education (코드 수정 및 등록 로직 수정)**
- 등록 시 해시태그 로직 추가
- 수정 시 해시태그 로직 추가
- Api return 상수값 enum 사용으로 변경하기
- 전체 조회 Dto 수정 ( 불필요한 항목(content) 제거)

#148 Api 작성 - Education (코드 수정 및 등록 로직 수정)

---

src/main/java/com/gabia/gyebalja/domain/Board.java
src/main/java/com/gabia/gyebalja/dto/board/BoardResponseDto.java
src/main/java/com/gabia/gyebalja/repository/BoardRepository.java
src/main/java/com/gabia/gyebalja/service/BoardService.java

#153 개선 - Board, Comment 양방향 구현

#153 개선 - Board, Comment 양방향 구현

---

src/main/java/com/gabia/gyebalja/controller/LikesApiController.java
src/main/java/com/gabia/gyebalja/repository/LikesRepository.java
src/main/java/com/gabia/gyebalja/service/LikesService.java

#152 개선 - Likes 조회 기능, 테스트코드 제외
- Likes 조회 기능 추가
- 테스트 코드 작성 X (테스트 데이터 삭제될 수 있어 작성하지 않았습니다.)

#152 개선 - Likes 조회 기능, 테스트코드 제외

---

src/test/java/com/gabia/gyebalja/board/BoardRepositoryTest.java
src/test/java/com/gabia/gyebalja/boardImg/BoardImgRepositoryTest.java
src/test/java/com/gabia/gyebalja/comment/CommentRepositoryTest.java
src/test/java/com/gabia/gyebalja/department/DepartmentRepositoryTest.java
src/test/java/com/gabia/gyebalja/likes/LikesRepositoryTest.java

#160 Api 개선 - @DataJpaTest 적용

---

src/main/java/com/gabia/gyebalja/domain/Board.java
src/main/java/com/gabia/gyebalja/dto/board/BoardResponseDto.java
src/main/java/com/gabia/gyebalja/dto/likes/LikesRequestDto.java
src/main/java/com/gabia/gyebalja/repository/BoardRepository.java
src/main/java/com/gabia/gyebalja/service/BoardService.java
src/main/java/com/gabia/gyebalja/service/LikesService.java
src/test/java/com/gabia/gyebalja/board/BoardControllerTest.java
src/test/java/com/gabia/gyebalja/board/BoardServiceTest.java
src/test/java/com/gabia/gyebalja/likes/LikesControllerTest.java
src/test/java/com/gabia/gyebalja/likes/LikesServiceTest.java

#159 Api 개선 - Board, Likes
1. Board 업데이트 로직 수정
- changeTitle, changeComment 등의 changeBoard 등으로 메소드 통합
- 테스트 코드 작성
<br>
2. Likes 빌더 수정
- 빌더 제거 (해결 X)
- 테스트 코드 작성
> ModelMapper

#159 Api 개선 - Board, Likes

---

src/main/java/com/gabia/gyebalja/dto/board/BoardResponseDto.java
src/main/java/com/gabia/gyebalja/dto/comment/CommentResponseDto.java

#158 Api 개선 - JsonFormat
- Board
- Comment 
Response DTO에 JsonFormat 적용

#158 Api 개선 - JsonFormat

---

src/main/java/com/gabia/gyebalja/domain/Board.java
src/main/java/com/gabia/gyebalja/dto/board/BoardResponseDto.java
src/main/java/com/gabia/gyebalja/dto/comment/CommentResponseDto.java
src/main/java/com/gabia/gyebalja/dto/likes/LikesRequestDto.java
src/main/java/com/gabia/gyebalja/repository/BoardRepository.java
src/main/java/com/gabia/gyebalja/service/BoardService.java
src/main/java/com/gabia/gyebalja/service/LikesService.java
src/test/java/com/gabia/gyebalja/board/BoardControllerTest.java
src/test/java/com/gabia/gyebalja/board/BoardRepositoryTest.java
src/test/java/com/gabia/gyebalja/board/BoardServiceTest.java
src/test/java/com/gabia/gyebalja/boardImg/BoardImgRepositoryTest.java
src/test/java/com/gabia/gyebalja/comment/CommentRepositoryTest.java
src/test/java/com/gabia/gyebalja/department/DepartmentRepositoryTest.java
src/test/java/com/gabia/gyebalja/likes/LikesControllerTest.java
src/test/java/com/gabia/gyebalja/likes/LikesRepositoryTest.java
src/test/java/com/gabia/gyebalja/likes/LikesServiceTest.java

#157 Api 개선
- 테스트 코드 어노테이션
- 빌더 -> 메소드
- Likes 조회 코드 추가
- Board Update 로직 수정
- JsonFormat 적용
> 추후 매퍼 활용

#157 Api 개선

---

src/main/java/com/gabia/gyebalja/dto/education/EducationAllResponseDto.java
src/main/java/com/gabia/gyebalja/dto/education/EducationDetailResponseDto.java
src/main/java/com/gabia/gyebalja/repository/EduTagRepository.java
src/main/java/com/gabia/gyebalja/service/EducationService.java

- EduTagRepository 코드 수정
- API 리스폰스에 날짜가 배열로 오는 것을 수정하기 위한 @JsonFormat 어노테이션 DTO에 추가

#170 Education Api 피드백 반영 - JsonFormat 추가 및 EduTag 리포지토리 중복 제거

---

src/main/java/com/gabia/gyebalja/controller/DepartmentApiController.java
src/main/java/com/gabia/gyebalja/service/DepartmentService.java
src/test/java/com/gabia/gyebalja/department/DepartmentControllerTest.java
src/test/java/com/gabia/gyebalja/department/DepartmentServiceTest.java

#166 Api 작성-Department 전체조회

---

src/test/java/com/gabia/gyebalja/category/CategoryControllerTest.java
src/test/java/com/gabia/gyebalja/category/CategoryRepositoryTest.java
src/test/java/com/gabia/gyebalja/category/CategoryServiceTest.java
src/test/java/com/gabia/gyebalja/common/HashTagRegularExpressionTest.java
src/test/java/com/gabia/gyebalja/education/EducationControllerTest.java
src/test/java/com/gabia/gyebalja/education/EducationRepositoryTest.java
src/test/java/com/gabia/gyebalja/education/EducationServiceTest.java
src/test/java/com/gabia/gyebalja/edutag/EduTagRepositoryTest.java
src/test/java/com/gabia/gyebalja/tag/TagControllerTest.java
src/test/java/com/gabia/gyebalja/tag/TagRepositoryTest.java
src/test/java/com/gabia/gyebalja/tag/TagServiceTest.java

- 코드 수정 및 작성에 의한 테스트 코드 변경 및 작성
- 해시태그 테스트 추가
- Repository Test는 @DataJpaTest로 변경

#174 Api 개선 - Education 코드리뷰 내용 일부 반영

---

src/main/java/com/gabia/gyebalja/controller/BoardApiController.java
src/main/java/com/gabia/gyebalja/dto/board/BoardAllResponseDto.java
src/main/java/com/gabia/gyebalja/dto/board/BoardDetailResponseDto.java
src/main/java/com/gabia/gyebalja/repository/BoardRepository.java
src/main/java/com/gabia/gyebalja/service/BoardService.java
src/test/java/com/gabia/gyebalja/board/BoardControllerTest.java
src/test/java/com/gabia/gyebalja/board/BoardRepositoryTest.java
src/test/java/com/gabia/gyebalja/board/BoardServiceTest.java

Api 개선 - Board
- Fetch Join , Pageable 사용 문제
-> 전체 조회 시에 comment 필요 없으므로 아예 삭제

#178 Api개선-Board

---

src/main/java/com/gabia/gyebalja/controller/BoardApiController.java
src/main/java/com/gabia/gyebalja/dto/board/BoardAllResponseDto.java
src/main/java/com/gabia/gyebalja/dto/board/BoardDetailResponseDto.java
src/main/java/com/gabia/gyebalja/repository/BoardRepository.java
src/main/java/com/gabia/gyebalja/service/BoardService.java
src/test/java/com/gabia/gyebalja/board/BoardControllerTest.java
src/test/java/com/gabia/gyebalja/board/BoardRepositoryTest.java
src/test/java/com/gabia/gyebalja/board/BoardServiceTest.java

#177 Api개선-Board (#179)
- BoardFetch Join , Pageable 사용 문제
-> 전체 조회 시에 comment 필요 없으므로 아예 삭제

#178 Api개선-Board (#179)

---

src/main/java/com/gabia/gyebalja/controller/StatisticsApiController.java
src/main/java/com/gabia/gyebalja/domain/Statistics.java
src/main/java/com/gabia/gyebalja/dto/statistics/StatisticsMainCategoryResponseDto.java
src/main/java/com/gabia/gyebalja/dto/statistics/StatisticsMainMonthResponseDto.java
src/main/java/com/gabia/gyebalja/dto/statistics/StatisticsMainResponseDto.java
src/main/java/com/gabia/gyebalja/dto/statistics/StatisticsMainTagResponseDto.java
src/main/java/com/gabia/gyebalja/dto/statistics/StatisticsMainYearResponseDto.java
src/main/java/com/gabia/gyebalja/repository/EduTagRepository.java
src/main/java/com/gabia/gyebalja/repository/EducationRepository.java
src/main/java/com/gabia/gyebalja/repository/StatisticsRepository.java
src/main/java/com/gabia/gyebalja/service/StatisticsService.java
src/test/java/com/gabia/gyebalja/statistics/StatisticsServiceTest.java

#168 Api 작성 - 통계 (메인)

---

src/main/java/com/gabia/gyebalja/repository/StatisticsRepository.java
src/main/java/com/gabia/gyebalja/service/StatisticsService.java
src/test/java/com/gabia/gyebalja/statistics/StatisticsControllerTest.java
src/test/java/com/gabia/gyebalja/statistics/StatisticsServiceTest.java

#185 Api 작성 - 메인 통계 (테스트코드)
- StatisticsRepository 일부 수정
- 서비스 테스트 코드 작성 (값 위주로 작성)
- 컨트롤러 테스트 코드 작성 (통신 위주로 작성)

#185 Api 작성 - 메인 통계 (테스트코드)

---

src/main/java/com/gabia/gyebalja/controller/StatisticsApiController.java
src/main/java/com/gabia/gyebalja/dto/statistics/StatisticsEducationCategoryResponseDto.java
src/main/java/com/gabia/gyebalja/dto/statistics/StatisticsEducationHourResponseDto.java
src/main/java/com/gabia/gyebalja/dto/statistics/StatisticsEducationMonthResponseDto.java
src/main/java/com/gabia/gyebalja/dto/statistics/StatisticsEducationRankResponseDto.java
src/main/java/com/gabia/gyebalja/dto/statistics/StatisticsEducationResponseDto.java
src/main/java/com/gabia/gyebalja/dto/statistics/StatisticsEducationTagResponseDto.java
src/main/java/com/gabia/gyebalja/repository/StatisticsRepository.java
src/main/java/com/gabia/gyebalja/repository/UserRepository.java
src/main/java/com/gabia/gyebalja/service/StatisticsService.java

**#181 Api 작성 - 통계 (개인교육관리)**
개인 교육관리 페이지 통계 Api 작성 완료
- 사용자 최고 관심사 카테고리 (누적)
- 부서 내 나의 등수 동점자는 같은 등수 처리 ( 당해년도 )
- 나의 총 교육시간과 회사 전체 인력당 평균시간 비교 (당해년도)
- 월별 교육시간, 교육건수 통계 ( 당해년도 )
- 관심 태그 Top 3 통계 (누적)

#181 Api 작성 - 통계 (개인교육관리)

---

src/main/java/com/gabia/gyebalja/controller/StatisticsApiController.java
src/main/java/com/gabia/gyebalja/dto/statistics/StatisticsMainCategoryResponseDto.java
src/main/java/com/gabia/gyebalja/dto/statistics/StatisticsMainMonthResponseDto.java
src/main/java/com/gabia/gyebalja/dto/statistics/StatisticsMainResponseDto.java
src/main/java/com/gabia/gyebalja/dto/statistics/StatisticsMainTagResponseDto.java
src/main/java/com/gabia/gyebalja/dto/statistics/StatisticsMainYearResponseDto.java
src/main/java/com/gabia/gyebalja/repository/StatisticsRepository.java
src/main/java/com/gabia/gyebalja/service/StatisticsService.java
src/test/java/com/gabia/gyebalja/statistics/StatisticsServiceTest.java

#194 통계(메인) 피드백 반영
- 통계 쿼리, 서비스 코드 피드백 개선

#194 통계(메인) 피드백 반영

---

src/main/java/com/gabia/gyebalja/controller/StatisticsApiController.java
src/main/java/com/gabia/gyebalja/dto/statistics/StatisticsMainCategoryResponseDto.java
src/main/java/com/gabia/gyebalja/dto/statistics/StatisticsMainMonthResponseDto.java
src/main/java/com/gabia/gyebalja/dto/statistics/StatisticsMainResponseDto.java
src/main/java/com/gabia/gyebalja/dto/statistics/StatisticsMainTagResponseDto.java
src/main/java/com/gabia/gyebalja/dto/statistics/StatisticsMainYearResponseDto.java
src/main/java/com/gabia/gyebalja/repository/StatisticsRepository.java
src/main/java/com/gabia/gyebalja/service/StatisticsService.java
src/test/java/com/gabia/gyebalja/statistics/StatisticsServiceTest.java

#194 통계(메인) 피드백 반영 (#195)
- 메인 화면 통계 쿼리, 서비스 피드백 개선

#194 통계(메인) 피드백 반영 (#195)

---

src/main/java/com/gabia/gyebalja/WebConfig.java
src/main/java/com/gabia/gyebalja/controller/BoardImgApiController.java

* #198 BoardImg 컨트롤러 작성, WebConfig 작성
* #198 resource 제거

#198 BoardImg 구현 (#199)

---

build.gradle
src/main/java/com/gabia/gyebalja/GyebaljaApplication.java
src/main/java/com/gabia/gyebalja/config/SwaggerConfiguration.java
src/main/java/com/gabia/gyebalja/config/WebConfig.java
src/main/java/com/gabia/gyebalja/config/auth/SecurityConfig.java
src/main/java/com/gabia/gyebalja/controller/GabiaLoginController.java
src/main/java/com/gabia/gyebalja/domain/User.java
src/main/java/com/gabia/gyebalja/service/GabiaService.java
src/main/java/com/gabia/gyebalja/vo/GabiaTokenVo.java
src/main/java/com/gabia/gyebalja/vo/GabiaUserInfoVo.java

**#184 OAuth로그인 구현 - JWT, Spring Security 구현 이전 커밋(GSON 추가, 하이웍스 API 연동, User 엔티티 칼럼 추가)**
- GSON 라이브러리 추가
- 하이웍스 API 연동 Controller, Service 작성
- 하이웍스 Api response 전용 Vo 작성 
- User 엔티티 변경 ( 가비아 고유 사용자 no, 영어이름 칼럼 추가)

#184 OAuth로그인 구현 - JWT, Spring Security 구현 이전 커밋

---

src/main/java/com/gabia/gyebalja/WebConfig.java
src/main/java/com/gabia/gyebalja/common/CookieBox.java
src/main/java/com/gabia/gyebalja/controller/GabiaLoginController.java
src/main/java/com/gabia/gyebalja/interceptor/JwtInterceptor.java
src/main/java/com/gabia/gyebalja/service/jwt/JwtServiceImpl.java

**#204 OAuth 로그인 구현 - 코드 수정 및 개선**
- 쿠키 Util 클래스 분리 
- Post, Put, Delete 시 발생하는 이슈 해결 
- 시크릿 키 분리
- 쿠키 유효시간 3시간으로 설정

#204 OAuth 로그인 구현 - 코드 수정 및 개선

---

src/main/java/com/gabia/gyebalja/controller/BoardImgApiController.java
src/main/java/com/gabia/gyebalja/dto/likes/LikesResponseDto.java
src/main/java/com/gabia/gyebalja/service/LikesService.java
src/test/java/com/gabia/gyebalja/likes/LikesServiceTest.java

#210 API 작성 - Board (BoardImg, Likes) - BoardImg, Likes
- Likes 단건 조회 수정 -> 데이터 없을 경우 에러가 아닌 true/false, id/-1 등의 값으로 반환
- BoardImg 업로드하는 파일명 변경 (랜덤하게)

#210 API 작성 - Board (BoardImg, Likes) - BoardImg, Likes

---

src/main/java/com/gabia/gyebalja/controller/BoardApiController.java
src/main/java/com/gabia/gyebalja/controller/BoardImgApiController.java
src/main/java/com/gabia/gyebalja/dto/likes/LikesResponseDto.java
src/main/java/com/gabia/gyebalja/interceptor/JwtInterceptor.java
src/main/java/com/gabia/gyebalja/service/LikesService.java
src/test/java/com/gabia/gyebalja/board/BoardControllerTest.java
src/test/java/com/gabia/gyebalja/boardImg/BoardImgRepositoryTest.java
src/test/java/com/gabia/gyebalja/category/CategoryControllerTest.java
src/test/java/com/gabia/gyebalja/category/CategoryRepositoryTest.java
src/test/java/com/gabia/gyebalja/category/CategoryServiceTest.java
src/test/java/com/gabia/gyebalja/comment/CommentControllerTest.java
src/test/java/com/gabia/gyebalja/comment/CommentRepositoryTest.java
src/test/java/com/gabia/gyebalja/department/DepartmentControllerTest.java
src/test/java/com/gabia/gyebalja/department/DepartmentRepositoryTest.java
src/test/java/com/gabia/gyebalja/education/EducationControllerTest.java
src/test/java/com/gabia/gyebalja/education/EducationRepositoryTest.java
src/test/java/com/gabia/gyebalja/education/EducationServiceTest.java
src/test/java/com/gabia/gyebalja/edutag/EduTagRepositoryTest.java
src/test/java/com/gabia/gyebalja/likes/LikesControllerTest.java
src/test/java/com/gabia/gyebalja/likes/LikesRepositoryTest.java
src/test/java/com/gabia/gyebalja/likes/LikesServiceTest.java
src/test/java/com/gabia/gyebalja/statistics/StatisticsControllerTest.java
src/test/java/com/gabia/gyebalja/tag/TagControllerTest.java
src/test/java/com/gabia/gyebalja/tag/TagRepositoryTest.java
src/test/java/com/gabia/gyebalja/tag/TagServiceTest.java
src/test/java/com/gabia/gyebalja/user/UserRepositoryTest.java

#212 API 작성 - Board (BoardImg, Likes) - 컨트롤러, 코드 정리
- 컨트롤러 테스트 시 인터셉터 해제
- 테스트 코드 정리

#212 API 작성 - Board (BoardImg, Likes) - 컨트롤러, 코드 정리

---

src/main/java/com/gabia/gyebalja/WebConfig.java
src/main/java/com/gabia/gyebalja/common/interceptor/JwtInterceptor.java
src/main/java/com/gabia/gyebalja/controller/GabiaLoginController.java
src/main/java/com/gabia/gyebalja/controller/UserApiController.java
src/main/java/com/gabia/gyebalja/domain/User.java
src/main/java/com/gabia/gyebalja/dto/user/UserRequestDto.java
src/main/java/com/gabia/gyebalja/dto/user/UserResponseDto.java
src/main/java/com/gabia/gyebalja/service/EducationService.java
src/main/java/com/gabia/gyebalja/service/GabiaService.java
src/main/java/com/gabia/gyebalja/service/UserService.java
src/main/java/com/gabia/gyebalja/service/jwt/JwtService.java
src/main/java/com/gabia/gyebalja/service/jwt/JwtServiceImpl.java
src/test/java/com/gabia/gyebalja/board/BoardControllerTest.java
src/test/java/com/gabia/gyebalja/board/BoardRepositoryTest.java
src/test/java/com/gabia/gyebalja/board/BoardServiceTest.java
src/test/java/com/gabia/gyebalja/boardImg/BoardImgRepositoryTest.java
src/test/java/com/gabia/gyebalja/comment/CommentControllerTest.java
src/test/java/com/gabia/gyebalja/comment/CommentRepositoryTest.java
src/test/java/com/gabia/gyebalja/comment/CommentServiceTest.java
src/test/java/com/gabia/gyebalja/education/EducationControllerTest.java
src/test/java/com/gabia/gyebalja/education/EducationRepositoryTest.java
src/test/java/com/gabia/gyebalja/education/EducationServiceTest.java
src/test/java/com/gabia/gyebalja/edutag/EduTagRepositoryTest.java
src/test/java/com/gabia/gyebalja/likes/LikesControllerTest.java
src/test/java/com/gabia/gyebalja/likes/LikesRepositoryTest.java
src/test/java/com/gabia/gyebalja/likes/LikesServiceTest.java
src/test/java/com/gabia/gyebalja/statistics/StatisticsServiceTest.java
src/test/java/com/gabia/gyebalja/user/UserRepositoryTest.java

#208 Api 작성 - User
- User 조회, 수정, 로그아웃 api 작성 (Controller, Service, Dto)
- User Entity 패스워드 컬럼 제거 (builder 수정으로 인한 코드 수정 추가)
- jwt 토큰 암호화 user_id에 이메일 추가

#208 Api 작성 - User

---

src/main/java/com/gabia/gyebalja/common/HashTagRegularExpression.java
src/main/java/com/gabia/gyebalja/controller/CategoryApiController.java
src/main/java/com/gabia/gyebalja/controller/EducationApiController.java
src/main/java/com/gabia/gyebalja/controller/TagApiController.java
src/main/java/com/gabia/gyebalja/controller/UserApiController.java
src/main/java/com/gabia/gyebalja/domain/Category.java
src/main/java/com/gabia/gyebalja/domain/EduTag.java
src/main/java/com/gabia/gyebalja/domain/Education.java
src/main/java/com/gabia/gyebalja/domain/Tag.java
src/main/java/com/gabia/gyebalja/dto/category/CategoryRequestDto.java
src/main/java/com/gabia/gyebalja/dto/education/EducationAllResponseDto.java
src/main/java/com/gabia/gyebalja/dto/edutag/EduTagResponseDto.java
src/main/java/com/gabia/gyebalja/repository/EducationRepository.java
src/main/java/com/gabia/gyebalja/repository/UserRepository.java
src/main/java/com/gabia/gyebalja/service/CategoryService.java
src/main/java/com/gabia/gyebalja/service/EducationService.java
src/main/java/com/gabia/gyebalja/service/TagService.java
src/main/java/com/gabia/gyebalja/service/jwt/JwtService.java
src/main/java/com/gabia/gyebalja/service/jwt/JwtServiceImpl.java
src/test/java/com/gabia/gyebalja/common/HashTagRegularExpressionTest.java
src/test/java/com/gabia/gyebalja/education/EducationServiceTest.java
src/test/java/com/gabia/gyebalja/tag/TagControllerTest.java

**#217 깃랩 동기화 및 User Api 추가**
- 코드 스타일 통일 
- 토큰으로 사용자 정보 조회 추가

#217 깃랩 동기화 및 User Api 추가

---

src/main/java/com/gabia/gyebalja/controller/ImageApiController.java
src/main/java/com/gabia/gyebalja/controller/UserApiController.java
src/main/java/com/gabia/gyebalja/service/ImageService.java

**#221 Api 작성 - 사용자 프로필 이미지 업로드 기능**

#221 Api 작성 - 사용자 프로필 이미지 업로드 기능

---

src/main/java/com/gabia/gyebalja/dto/board/BoardDetailResponseDto.java

#225 BoardDetailResponseDto 수정 - 필드 추가

#225 BoardDetailResponseDto 수정 - 필드 추가

---

.gitignore
src/main/java/com/gabia/gyebalja/service/log/LogService.java
src/main/resources/logback-spring.xml

#219 Logger - 기능 구현

---

src/main/java/com/gabia/gyebalja/dto/board/BoardDetailResponseDto.java

#236 BoardDetailResponseDto - User Profile Image 추가

#236 BoardDetailResponseDto - User Profile Image 추가

---

src/main/java/com/gabia/gyebalja/common/HashTagRegularExpression.java
src/main/java/com/gabia/gyebalja/service/EducationService.java
src/test/java/com/gabia/gyebalja/common/HashTagRegularExpressionTest.java

**#242 Fix - 해시태그 중복 문자열 제거 로직 추가 및 관련 테스트 코드 작성**

#242 Fix - 해시태그 중복 문자열 제거 로직 추가 및 관련 테스트 코드 작성

---

src/main/java/com/gabia/gyebalja/controller/GabiaLoginController.java

**#246 Hotfixes - 리다이렉트 버그 수정**

#246 Hotfixes - 리다이렉트 버그 수정

---

src/test/java/com/gabia/gyebalja/GyebaljaApplicationTests.java

#248 Hotfixes - 테스트 yml 설정 누락 부분 추가

#248 Hotfixes - 테스트 yml 설정 누락 부분 추가

---

.gitignore
src/main/java/com/gabia/gyebalja/controller/CommentApiController.java
src/main/java/com/gabia/gyebalja/controller/GabiaLoginController.java
src/main/java/com/gabia/gyebalja/service/CommentService.java
src/main/resources/logback-spring.xml
src/test/java/com/gabia/gyebalja/comment/CommentControllerTest.java
src/test/java/com/gabia/gyebalja/comment/CommentServiceTest.java

#252 Feedback - 기능 개선 (댓글 전체조회)

---

src/main/java/com/gabia/gyebalja/service/JwtService.java
src/test/java/com/gabia/gyebalja/edutag/EduTagRepositoryTest.java
src/test/java/com/gabia/gyebalja/tag/TagRepositoryTest.java
src/test/java/com/gabia/gyebalja/user/UserControllerTest.java
src/test/java/com/gabia/gyebalja/user/UserRepositoryTest.java
src/test/java/com/gabia/gyebalja/user/UserServiceTest.java

**#259 테스트 코드 작성 - User**
- UserRepositoryTest 수정
- UserServiceTest 작성
- UserControllerTest 작성

#259 테스트 코드 작성 - User

---

src/main/java/com/gabia/gyebalja/service/JwtService.java
src/test/java/com/gabia/gyebalja/edutag/EduTagRepositoryTest.java
src/test/java/com/gabia/gyebalja/statistics/StatisticsControllerTest.java
src/test/java/com/gabia/gyebalja/statistics/StatisticsServiceTest.java
src/test/java/com/gabia/gyebalja/tag/TagRepositoryTest.java
src/test/java/com/gabia/gyebalja/user/UserControllerTest.java
src/test/java/com/gabia/gyebalja/user/UserRepositoryTest.java
src/test/java/com/gabia/gyebalja/user/UserServiceTest.java

#256 테스트 코드 작성 - User, 통계

---

src/main/java/com/gabia/gyebalja/common/CookieBox.java
src/main/java/com/gabia/gyebalja/common/interceptor/JwtInterceptor.java
src/main/java/com/gabia/gyebalja/controller/CategoryApiController.java
src/main/java/com/gabia/gyebalja/service/CategoryService.java
src/main/java/com/gabia/gyebalja/service/EducationService.java
src/main/java/com/gabia/gyebalja/service/TagService.java
src/main/java/com/gabia/gyebalja/service/UserService.java
src/test/java/com/gabia/gyebalja/category/CategoryControllerTest.java
src/test/java/com/gabia/gyebalja/category/CategoryRepositoryTest.java
src/test/java/com/gabia/gyebalja/category/CategoryServiceTest.java
src/test/java/com/gabia/gyebalja/education/EducationControllerTest.java
src/test/java/com/gabia/gyebalja/edutag/EduTagRepositoryTest.java
src/test/java/com/gabia/gyebalja/user/UserRepositoryTest.java

#264 Refactoring - 코드 정리 2

---

src/main/java/com/gabia/gyebalja/service/ImageService.java
src/main/java/com/gabia/gyebalja/service/JwtService.java

<h3>Merge develop ver1.2 - 20200317</h3>
**주요 구현 요소들**
- Hostname -> IP 변경 (api.gyeblja.com -> 211.53.209.130)

Merge develop ver1.2 - 20200317

---

src/main/java/com/gabia/gyebalja/controller/RankApiController.java
src/main/java/com/gabia/gyebalja/domain/User.java
src/main/java/com/gabia/gyebalja/dto/rank/RankResponseDto.java
src/main/java/com/gabia/gyebalja/repository/RankRepository.java
src/main/java/com/gabia/gyebalja/service/RankService.java
src/test/java/com/gabia/gyebalja/rank/RankRepositoryTest.java

**#273 Api 작성 - 부서인원 Rank Api**

#273 Api 작성 - 부서인원 Rank Api

---

src/main/java/com/gabia/gyebalja/domain/User.java
src/main/java/com/gabia/gyebalja/dto/rank/RankResponseDto.java
src/main/java/com/gabia/gyebalja/repository/RankRepository.java
src/main/java/com/gabia/gyebalja/service/RankService.java

**#275 Api 개선 - 부서별 Rank 피드백 반영**
- 양방향 관계 해제
- 유저 쿼리나가는 것 없애기 (성능 개선)
- JPQL 수정 (연도 조건 추가)

#275 Api 개선 - 부서별 Rank 피드백 반영

---

src/main/java/com/gabia/gyebalja/common/CookieBox.java
src/main/java/com/gabia/gyebalja/service/JwtService.java

#279 Api 개선 - 로그아웃 피드백 반영

---

src/test/java/com/gabia/gyebalja/rank/RankControllerTest.java
src/test/java/com/gabia/gyebalja/rank/RankServiceTest.java

**#277 Api 작성 - 부서별 Rank 테스트 코드 작성 (Service, Controller, Repository)**
- RankRepositoryTest
- RankServiceTest
- RankControllerTest

#277 Api 작성 - 부서별 Rank 테스트 코드 작성 (Service, Controller, Repository)

---

src/main/java/com/gabia/gyebalja/controller/GabiaLoginController.java
src/main/java/com/gabia/gyebalja/service/JwtService.java

#282 로그아웃 피드백 반영
